/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrijavaRouteImport } from './routes/prijava'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PorudzbinaIdRouteImport } from './routes/porudzbina.$id'
import { Route as AdminTroskoviRouteImport } from './routes/admin.troskovi'
import { Route as AdminPostavkeRouteImport } from './routes/admin.postavke'
import { Route as AdminIzvjestajiRouteImport } from './routes/admin.izvjestaji'
import { Route as AdminFormatiRouteImport } from './routes/admin.formati'
import { Route as AdminPorudzbineIndexRouteImport } from './routes/admin.porudzbine.index'
import { Route as AdminPorudzbineIdRouteImport } from './routes/admin.porudzbine.$id'
import { Route as ApiPublicHooksCleanupImagesRouteImport } from './routes/api/public/hooks/cleanup-images'

const PrijavaRoute = PrijavaRouteImport.update({
  id: '/prijava',
  path: '/prijava',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PorudzbinaIdRoute = PorudzbinaIdRouteImport.update({
  id: '/porudzbina/$id',
  path: '/porudzbina/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTroskoviRoute = AdminTroskoviRouteImport.update({
  id: '/troskovi',
  path: '/troskovi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostavkeRoute = AdminPostavkeRouteImport.update({
  id: '/postavke',
  path: '/postavke',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIzvjestajiRoute = AdminIzvjestajiRouteImport.update({
  id: '/izvjestaji',
  path: '/izvjestaji',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormatiRoute = AdminFormatiRouteImport.update({
  id: '/formati',
  path: '/formati',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPorudzbineIndexRoute = AdminPorudzbineIndexRouteImport.update({
  id: '/porudzbine/',
  path: '/porudzbine/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPorudzbineIdRoute = AdminPorudzbineIdRouteImport.update({
  id: '/porudzbine/$id',
  path: '/porudzbine/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksCleanupImagesRoute =
  ApiPublicHooksCleanupImagesRouteImport.update({
    id: '/api/public/hooks/cleanup-images',
    path: '/api/public/hooks/cleanup-images',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/prijava': typeof PrijavaRoute
  '/admin/formati': typeof AdminFormatiRoute
  '/admin/izvjestaji': typeof AdminIzvjestajiRoute
  '/admin/postavke': typeof AdminPostavkeRoute
  '/admin/troskovi': typeof AdminTroskoviRoute
  '/porudzbina/$id': typeof PorudzbinaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/porudzbine/$id': typeof AdminPorudzbineIdRoute
  '/admin/porudzbine/': typeof AdminPorudzbineIndexRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prijava': typeof PrijavaRoute
  '/admin/formati': typeof AdminFormatiRoute
  '/admin/izvjestaji': typeof AdminIzvjestajiRoute
  '/admin/postavke': typeof AdminPostavkeRoute
  '/admin/troskovi': typeof AdminTroskoviRoute
  '/porudzbina/$id': typeof PorudzbinaIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/porudzbine/$id': typeof AdminPorudzbineIdRoute
  '/admin/porudzbine': typeof AdminPorudzbineIndexRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/prijava': typeof PrijavaRoute
  '/admin/formati': typeof AdminFormatiRoute
  '/admin/izvjestaji': typeof AdminIzvjestajiRoute
  '/admin/postavke': typeof AdminPostavkeRoute
  '/admin/troskovi': typeof AdminTroskoviRoute
  '/porudzbina/$id': typeof PorudzbinaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/porudzbine/$id': typeof AdminPorudzbineIdRoute
  '/admin/porudzbine/': typeof AdminPorudzbineIndexRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/prijava'
    | '/admin/formati'
    | '/admin/izvjestaji'
    | '/admin/postavke'
    | '/admin/troskovi'
    | '/porudzbina/$id'
    | '/admin/'
    | '/admin/porudzbine/$id'
    | '/admin/porudzbine/'
    | '/api/public/hooks/cleanup-images'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prijava'
    | '/admin/formati'
    | '/admin/izvjestaji'
    | '/admin/postavke'
    | '/admin/troskovi'
    | '/porudzbina/$id'
    | '/admin'
    | '/admin/porudzbine/$id'
    | '/admin/porudzbine'
    | '/api/public/hooks/cleanup-images'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/prijava'
    | '/admin/formati'
    | '/admin/izvjestaji'
    | '/admin/postavke'
    | '/admin/troskovi'
    | '/porudzbina/$id'
    | '/admin/'
    | '/admin/porudzbine/$id'
    | '/admin/porudzbine/'
    | '/api/public/hooks/cleanup-images'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrijavaRoute: typeof PrijavaRoute
  PorudzbinaIdRoute: typeof PorudzbinaIdRoute
  ApiPublicHooksCleanupImagesRoute: typeof ApiPublicHooksCleanupImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prijava': {
      id: '/prijava'
      path: '/prijava'
      fullPath: '/prijava'
      preLoaderRoute: typeof PrijavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/porudzbina/$id': {
      id: '/porudzbina/$id'
      path: '/porudzbina/$id'
      fullPath: '/porudzbina/$id'
      preLoaderRoute: typeof PorudzbinaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/troskovi': {
      id: '/admin/troskovi'
      path: '/troskovi'
      fullPath: '/admin/troskovi'
      preLoaderRoute: typeof AdminTroskoviRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/postavke': {
      id: '/admin/postavke'
      path: '/postavke'
      fullPath: '/admin/postavke'
      preLoaderRoute: typeof AdminPostavkeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/izvjestaji': {
      id: '/admin/izvjestaji'
      path: '/izvjestaji'
      fullPath: '/admin/izvjestaji'
      preLoaderRoute: typeof AdminIzvjestajiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formati': {
      id: '/admin/formati'
      path: '/formati'
      fullPath: '/admin/formati'
      preLoaderRoute: typeof AdminFormatiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/porudzbine/': {
      id: '/admin/porudzbine/'
      path: '/porudzbine'
      fullPath: '/admin/porudzbine/'
      preLoaderRoute: typeof AdminPorudzbineIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/porudzbine/$id': {
      id: '/admin/porudzbine/$id'
      path: '/porudzbine/$id'
      fullPath: '/admin/porudzbine/$id'
      preLoaderRoute: typeof AdminPorudzbineIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/cleanup-images': {
      id: '/api/public/hooks/cleanup-images'
      path: '/api/public/hooks/cleanup-images'
      fullPath: '/api/public/hooks/cleanup-images'
      preLoaderRoute: typeof ApiPublicHooksCleanupImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFormatiRoute: typeof AdminFormatiRoute
  AdminIzvjestajiRoute: typeof AdminIzvjestajiRoute
  AdminPostavkeRoute: typeof AdminPostavkeRoute
  AdminTroskoviRoute: typeof AdminTroskoviRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPorudzbineIdRoute: typeof AdminPorudzbineIdRoute
  AdminPorudzbineIndexRoute: typeof AdminPorudzbineIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormatiRoute: AdminFormatiRoute,
  AdminIzvjestajiRoute: AdminIzvjestajiRoute,
  AdminPostavkeRoute: AdminPostavkeRoute,
  AdminTroskoviRoute: AdminTroskoviRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPorudzbineIdRoute: AdminPorudzbineIdRoute,
  AdminPorudzbineIndexRoute: AdminPorudzbineIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PrijavaRoute: PrijavaRoute,
  PorudzbinaIdRoute: PorudzbinaIdRoute,
  ApiPublicHooksCleanupImagesRoute: ApiPublicHooksCleanupImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
