/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ApiPublicHooksCleanupImagesRouteImport } from './routes/api/public/hooks/cleanup-images'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupImagesRoute =
  ApiPublicHooksCleanupImagesRouteImport.update({
    id: '/api/public/hooks/cleanup-images',
    path: '/api/public/hooks/cleanup-images',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order/$id': typeof OrderIdRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order/$id': typeof OrderIdRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order/$id': typeof OrderIdRoute
  '/api/public/hooks/cleanup-images': typeof ApiPublicHooksCleanupImagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/order/$id' | '/api/public/hooks/cleanup-images'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/order/$id' | '/api/public/hooks/cleanup-images'
  id: '__root__' | '/' | '/order/$id' | '/api/public/hooks/cleanup-images'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderIdRoute: typeof OrderIdRoute
  ApiPublicHooksCleanupImagesRoute: typeof ApiPublicHooksCleanupImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-images': {
      id: '/api/public/hooks/cleanup-images'
      path: '/api/public/hooks/cleanup-images'
      fullPath: '/api/public/hooks/cleanup-images'
      preLoaderRoute: typeof ApiPublicHooksCleanupImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderIdRoute: OrderIdRoute,
  ApiPublicHooksCleanupImagesRoute: ApiPublicHooksCleanupImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
